category: TF Generated Tools
description: Runs Planemo lint on any ToolFactory xml history file
name: planemo_lint
owner: admin
synopsis: Runs Planemo lint on any ToolFactory xml history file
type: unrestricted
