version: "3.7"
services:
  galaxy-server:
    image: quay.io/fubar2/toolfactory-galaxy:latest
    build: toolfactory-galaxy
    environment:
      - GALAXY_DEFAULT_ADMIN_USER=admin
      - GALAXY_DEFAULT_ADMIN_EMAIL=admin@galaxy.org
      - GALAXY_DEFAULT_ADMIN_PASSWORD=password
      - GALAXY_DEFAULT_ADMIN_KEY=fakekey
    privileged: True
    ports:
      - 21:21
      - 8080:80
      - 8800:8800
      - 9002:9002
    hostname: galaxy-server
    volumes:
      # This is the directory where all your files from Galaxy will be stored
      # on your host system
      - ${EXPORT_DIR:-./export}/:/export/:delegated
      - /var/run/docker.sock:/var/run/docker.sock
      - shared_galaxy:/galaxy-central
      - config:/etc/galaxy
  #post install configution with tools, history and planemo tester triggered by an exposed rpyc server function
  toolfactory-configurator:
    image: quay.io/fubar2/toolfactory-configurator:latest
    build: toolfactory-configurator
    privileged: True
    hostname: planemo-server
    environment:
      - EXPORT_DIR=${EXPORT_DIR:-./export}
      - GALAXY_CONFIG_ADMIN_USERS=admin@galaxy.org
    depends_on:
      - galaxy-server
    volumes:
      - ${EXPORT_DIR:-./export}/:/export/:delegated
      - /var/run/docker.sock:/var/run/docker.sock
      - shared_galaxy:/galaxy-central
      - config:/etc/galaxy
networks:
  default:
    driver: bridge
    attachable: true
volumes:
  shared_galaxy:
  config:

