---
- name: Ensure apt-transport-https is installed.
  apt: name=apt-transport-https state={{ galaxy_extras_apt_package_state }}

- name: "Yarn: Make sure package key is present"
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: "Yarn: Add Debian/Ubuntu package to sources list"
  apt_repository:
    repo: "deb http://dl.yarnpkg.com/debian/ stable main"
    state: "{{ galaxy_extras_apt_package_state }}"

- name: "Yarn: Install"
  apt: pkg=yarn state=latest update_cache=true
