- name: "Install uwsgi for galaxy"
  pip: 
    name: uwsgi
    version: 2.0.15
    virtualenv: "{{ galaxy_venv_dir }}"
    virtualenv_command: "{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
    extra_args: "--index-url https://wheels.galaxyproject.org/ --extra-index-url https://pypi.python.org/simple"
  become: True
  become_user: "{{ galaxy_user_name }}"
