category: TF Generated Tools
description: positional parameter example for a python script.
name: pyrev_pos_test
owner: admin
synopsis: positional parameter example for a python script.
type: unrestricted
